# remote_theme: jekyll/minima
# OR remove the line entirely
include:
  - docs/gimp/arch/Gimp/*.a3d.md
  - docs/gimp/arch/Gegl/*.a3d.md
  - docs/gimp/arch/GimpUi/*.a3d.md
title: A Cubed GIMP Docs
description: GIMP 3 Python and PDB class references by AÂ³BS
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: pretty
